"""Added Skill and added Relationship

Revision ID: 74d161cb9931
Revises: 7d3a8f1cdc57
Create Date: 2024-05-05 00:20:41.944001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d161cb9931'
down_revision: Union[str, None] = '7d3a8f1cdc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skill_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_skill_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skill_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_skill_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
